"""the fields 'name' in the author table and 'title' in the book table are now unique

Revision ID: 9d3c8ea9ce21
Revises: f65ea21ee1a9
Create Date: 2025-03-05 16:01:49.695279

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d3c8ea9ce21"
down_revision: Union[str, None] = "f65ea21ee1a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "authors", ["name"])
    op.create_unique_constraint(None, "books", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "books", type_="unique")
    op.drop_constraint(None, "authors", type_="unique")
    # ### end Alembic commands ###
