"""add unique constraint on book_id and user_id in book_loans

Revision ID: 703debaf2dd6
Revises: 9d3c8ea9ce21
Create Date: 2025-03-12 11:40:29.758471

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "703debaf2dd6"
down_revision: Union[str, None] = "9d3c8ea9ce21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_book_user", "book_loans", ["book_id", "user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_book_user", "book_loans", type_="unique")
    # ### end Alembic commands ###
